# Generated by Django 5.1.7 on 2025-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_rename_taks_tag_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="todo_list.tag"
            ),
        ),
    ]
